name: Build and Push Docker Image

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  Builds_Docker_Image:
    needs: Explore-GitHub-Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Print message before building Docker image
        run: echo "Building Docker image..."

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/mainapp:latest -f docker/Build.DockerFile .

      - name: Print message before pushing Docker image
        run: echo "Pushing Docker image to GitHub Container Registry..."

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/mainapp:latest

      - name: Print completion message
        run: echo "Docker image build and push completed successfully."
  
  Deploying_to_Kubernetes:
    needs: Builds_Docker_Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          ls -l
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
  
      - name: Create Kubernetes secret for GitHub Container Registry
        run: |
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ secrets.GHCR_USERNAME }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }} \
            --docker-email=${{ secrets.GHCR_EMAIL }} \
          || kubectl get secret ghcr-secret
  
      - name: Apply Kubernetes deployment
        run: kubectl apply -f infrastructure/K8S/deployments/main-app-deployment.yml
  
      - name: Force rollout of the deployment to use the latest image
        run: kubectl rollout restart deployment/mainapp-deployment